namespace AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
{
    class AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    {
        protected char AAAAAAAAAAAAAA = '\n';
        protected char AAAAAAAAAAAAAAA = '(';
        protected char AAAAAAAAAAAAAAAA = ')';
        protected int AAAAAAAAA = 720;
        protected string AAAAAAAAAAAA;
        protected double AAAAAAAAAAAAA;
    }
}
