using System;
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
using System.Collections.Generic;

namespace AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
{
    class AAAAAAAAAAAAAAAAAAAAAAAAAAA:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    {
        public double AAAAAAAAAAAAAAAAAAAA;
        public AAAAAAAAAAAAAAAAAAAAAAAAAAA(string AAAAA, double AAAAAAAAAA)
        {
            this.AAAAAAAAAAAA = AAAAA;
            this.AAAAAAAAAAAAA = AAAAAAAAAA;
        }

        public void AAAAAAAAAA()
        {
            Console.WriteLine($"{AAAAAAAAAAAAAA}AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA: {AAAAAAAAAAAA}{AAAAAAAAAAAAAA}AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA: {AAAAAAAAAAAAA} A/hour{AAAAAAAAAAAAAA}{AAAAAAAAAAAAAA}");
        }

        public double AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA()
        {
            return Math.Round((AAAAAAAAAAAAAAAAAAAA / AAAAAAAAAAAAA) * AAAAAAAAAAAAAAA + AAAAAAAAA + AAAAAAAAA + AAAAAAAAA + AAAAAAAAA + AAAAAAAAA + AAAAAAAAAAAAAAAA);
        }
    }

    class AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    {
        static void Main()
        {
            int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 0;
            Dictionary<string, double> AAAAAAAAAAAAAAAAAAAAAAAAAA = new Dictionary<string, double>();
            double AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
            string AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;

            Console.Write("AAAAAAAA AAAAAA AAAAAA A AAAAAAAAAAA: ");
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = Convert.ToDouble(Console.ReadLine());

            while(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA < 4)
            {
                Console.Write("AAAAAAAAAA AAAAAAAAAAA AAAAAAAAAAAAA: ");
                while (true)
                {
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = Console.ReadLine();
                    if (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.Length == 0 || AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.Length > 25)
                    {
                        Console.Write("AAAAAAAAAAAAAAA не больше 25 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ");
                    }
                    else
                    {
                        break;
                    }
                }
                Console.Write("AAAAAAAAAAAAAAAAAAAAAAAAAAA SPEEEEEEED: ");
                while (true)
                {
                    double AAAAAAAAAAAAAAAAAAAAAAAAA = Convert.ToDouble(Console.ReadLine());
                    if (AAAAAAAAAAAAAAAAAAAAAAAAA < 1 || AAAAAAAAAAAAAAAAAAAAAAAAA > 500)
                    {
                        Console.Write("AAAAAAAAAAAAAAAAAAAAAAAAAA: ");
                    }
                    else
                    {
                        Console.WriteLine($"\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAA {AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA + 1}");
                        AAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAA = new AAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAAAAAAAAAAA);
                        AAAAAAAAAAAAAAA.AAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
                        AAAAAAAAAAAAAAA.AAAAAAAAAA();


                        double AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAA.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA();
                        AAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;


                        break;
                    }
                }
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++;
            }

            Console.WriteLine("\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAA:\n");
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAA);




            static void AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(Dictionary<string, double> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
            {
                int AAAAAAAAAAAA, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
                double AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = double.MaxValue;
                string AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = "";
                // AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                foreach (var AAAAAAAAAAAAAAAAAAAAAAAAAAA in AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
                {
                    if (AAAAAAAAAAAAAAAAAAAAAAAAAAA.Value < AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
                    {
                        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAAAAAAAAAAAAAA.Value;
                        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAAAAAAAAAAAAAA.Key;

                    }
                    AAAAAAAAAAAA = Convert.ToInt32(AAAAAAAAAAAAAAAAAAAAAAAAAAA.Value / 3600);
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = Convert.ToInt32((AAAAAAAAAAAAAAAAAAAAAAAAAAA.Value % 3600) / 60);
                    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = Convert.ToInt32(AAAAAAAAAAAAAAAAAAAAAAAAAAA.Value % 60);
                    Console.WriteLine($"AAAAAAAAAAAAA AAAAAAAAAA: {AAAAAAAAAAAAAAAAAAAAAAAAAAA.Key}, AAAAAAAAA: {AAAAAAAAAAAA} AAAAAAAAAAA, {AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, {AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
                }
                AAAAAAAAAAAA = Convert.ToInt32(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA / 3600);
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = Convert.ToInt32((AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA % 3600) / 60);
                AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = Convert.ToInt32(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA % 60);
                Console.WriteLine($"AAAAAAAAAAAAAAAAAAA AAAAAAA AAA AA AAAAAAAAAAA: '{AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}'. AAA AAAAAAAAA AAAAAAAA AA: {AAAAAAAAAAAA} AAAAA, {AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} AAAAAA, {AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA} AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
            }
        }
    }
}


